services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: amdox
      POSTGRES_PASSWORD: amdox123
      POSTGRES_DB: amdox_erp
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "8080:8080"
