'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import {
  Activity,
  FileText,
  Package,
  RefreshCw,
  ShoppingCart,
  Users,
  Wallet,
} from 'lucide-react';
import api from '../../lib/api';

interface AuditUser {
  id: string;
  name?: string;
  email?: string;
  role?: string;
}

interface AuditLog {
  id: string;
  module: string;
  action: string;
  entityType: string;
  entityId?: string;
  description?: string;
  createdAt: string;
  user?: AuditUser;
}

function formatDateTime(value?: string) {
  if (!value) {
    return 'Date unavailable';
  }

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return 'Date unavailable';
  }

  return date.toLocaleString('en-IN', {
    dateStyle: 'medium',
    timeStyle: 'short',
  });
}

function formatLabel(value?: string) {
  if (!value) {
    return 'Activity';
  }

  return value
    .replace(/_/g, ' ')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .toLowerCase()
    .replace(/\b\w/g, (character) =>
      character.toUpperCase(),
    );
}

function getAuditDestination(log: AuditLog) {
  const module = log.module.toUpperCase();
  const entity = log.entityType.toLowerCase();

  if (module.includes('FINANCE')) {
    if (entity.includes('invoice')) {
      return '/finance/invoices';
    }

    if (
      entity.includes('transaction') ||
      entity.includes('journal')
    ) {
      return '/finance/transactions';
    }

    return '/finance';
  }

  if (module.includes('HR')) {
    if (entity.includes('leave')) {
      return '/hr/leaves';
    }

    if (entity.includes('payroll')) {
      return '/hr/payroll';
    }

    return '/hr/employees';
  }

  if (
    module.includes('SUPPLY') ||
    module.includes('INVENTORY')
  ) {
    if (
      entity.includes('order') ||
      entity.includes('purchase')
    ) {
      return '/supply-chain/orders';
    }

    if (
      entity.includes('vendor') ||
      entity.includes('supplier')
    ) {
      return '/supply-chain/suppliers';
    }

    return '/supply-chain/inventory';
  }

  return '/dashboard';
}

export default function AuditLogsPage() {
  const router = useRouter();

  const [logs, setLogs] = useState<AuditLog[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState('');
  const [moduleFilter, setModuleFilter] =
    useState('ALL');

  const loadAuditLogs = useCallback(
    async (isRefresh = false) => {
      try {
        if (isRefresh) {
          setRefreshing(true);
        } else {
          setLoading(true);
        }

        setError('');

        const response = await api.get('/audit-logs');
        setLogs(
          Array.isArray(response.data)
            ? response.data
            : [],
        );
      } catch (err) {
        console.error(
          'Audit activity loading failed:',
          err,
        );
        setError(
          'Could not load audit activity. Please log in again and retry.',
        );
      } finally {
        setLoading(false);
        setRefreshing(false);
      }
    },
    [],
  );

  useEffect(() => {
    loadAuditLogs();
  }, [loadAuditLogs]);

  const availableModules = useMemo(
    () =>
      Array.from(
        new Set(logs.map((log) => log.module)),
      ),
    [logs],
  );

  const filteredLogs = useMemo(() => {
    if (moduleFilter === 'ALL') {
      return logs;
    }

    return logs.filter(
      (log) => log.module === moduleFilter,
    );
  }, [logs, moduleFilter]);

  const getIcon = (log: AuditLog) => {
    const module = log.module.toUpperCase();
    const entity = log.entityType.toLowerCase();

    if (module.includes('FINANCE')) {
      return <Wallet size={20} />;
    }

    if (module.includes('HR')) {
      return <Users size={20} />;
    }

    if (entity.includes('order')) {
      return <ShoppingCart size={20} />;
    }

    if (module.includes('SUPPLY')) {
      return <Package size={20} />;
    }

    return <FileText size={20} />;
  };

  const getModuleClass = (module: string) => {
    const normalizedModule = module.toUpperCase();

    if (normalizedModule.includes('HR')) {
      return 'bg-blue-100 text-blue-700';
    }

    if (normalizedModule.includes('FINANCE')) {
      return 'bg-green-100 text-green-700';
    }

    if (normalizedModule.includes('SUPPLY')) {
      return 'bg-purple-100 text-purple-700';
    }

    return 'bg-slate-100 text-slate-700';
  };

  return (
    <section className="p-8">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-3">
            <Activity size={30} />

            <h1 className="text-4xl font-bold">
              Audit Activity
            </h1>
          </div>

          <p className="mt-2 text-gray-600">
            Immutable activity records generated by ERP
            operations.
          </p>
        </div>

        <button
          type="button"
          onClick={() => loadAuditLogs(true)}
          disabled={refreshing}
          className="flex items-center gap-2 rounded-lg bg-slate-900 px-5 py-3 text-white hover:bg-slate-700 disabled:opacity-50"
        >
          <RefreshCw
            size={18}
            className={
              refreshing ? 'animate-spin' : ''
            }
          />

          {refreshing ? 'Refreshing...' : 'Refresh'}
        </button>
      </div>

      <div className="mt-8 rounded-xl bg-white p-6 shadow">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <p className="text-sm text-gray-500">
              Total recorded activities
            </p>

            <p className="mt-1 text-3xl font-bold">
              {logs.length}
            </p>
          </div>

          <select
            value={moduleFilter}
            onChange={(event) =>
              setModuleFilter(event.target.value)
            }
            className="rounded-lg border border-gray-300 px-4 py-3"
          >
            <option value="ALL">All Modules</option>

            {availableModules.map((module) => (
              <option key={module} value={module}>
                {formatLabel(module)}
              </option>
            ))}
          </select>
        </div>
      </div>

      {loading && (
        <div className="mt-8 rounded-xl bg-white p-8 text-center shadow">
          <RefreshCw className="mx-auto animate-spin text-gray-500" />

          <p className="mt-3 text-gray-500">
            Loading audit activity...
          </p>
        </div>
      )}

      {error && !loading && (
        <div className="mt-8 rounded-xl bg-red-50 p-5 text-red-600">
          {error}
        </div>
      )}

      {!loading &&
        !error &&
        filteredLogs.length === 0 && (
          <div className="mt-8 rounded-xl bg-white p-8 text-center text-gray-500 shadow">
            No audit activity has been recorded yet.
          </div>
        )}

      {!loading &&
        !error &&
        filteredLogs.length > 0 && (
          <div className="mt-8 space-y-4">
            {filteredLogs.map((log) => (
              <div
                key={log.id}
                role="button"
                tabIndex={0}
                onClick={() =>
                  router.push(getAuditDestination(log))
                }
                onKeyDown={(event) => {
                  if (
                    event.key === 'Enter' ||
                    event.key === ' '
                  ) {
                    event.preventDefault();
                    router.push(
                      getAuditDestination(log),
                    );
                  }
                }}
                className="cursor-pointer rounded-xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-md"
              >
                <div className="flex flex-wrap items-start justify-between gap-4">
                  <div className="flex gap-4">
                    <div className="mt-1 rounded-lg bg-slate-100 p-3 text-slate-700">
                      {getIcon(log)}
                    </div>

                    <div>
                      <div className="flex flex-wrap items-center gap-2">
                        <h2 className="font-semibold">
                          {formatLabel(log.action)}
                        </h2>

                        <span
                          className={`rounded-full px-3 py-1 text-xs font-medium ${getModuleClass(
                            log.module,
                          )}`}
                        >
                          {formatLabel(log.module)}
                        </span>
                      </div>

                      <p className="mt-2 text-gray-700">
                        {log.description ||
                          `${formatLabel(
                            log.entityType,
                          )} activity`}
                      </p>

                      <p className="mt-2 text-sm text-gray-500">
                        Performed by:{' '}
                        {log.user?.name ||
                          log.user?.email ||
                          'System'}
                      </p>

                      <p className="mt-2 text-sm font-medium text-blue-600">
                        Click to view related records
                      </p>
                    </div>
                  </div>

                  <p className="text-sm text-gray-500">
                    {formatDateTime(log.createdAt)}
                  </p>
                </div>
              </div>
            ))}
          </div>
        )}
    </section>
  );
}